<?php

namespace ProiectPHPAdvanced\TemaBundle\Repository;

use ProiectPHPAdvanced\TemaBundle\Entity\Comments;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{
	public function addComment($data,$id){
	
		$comment = new Comments();
		$comment->setComment($data['title']);
		$comment->setArticleId($id);
		$comment->setDate(new \DateTime("now"));
		
		$this->_em->persist($comment);
		
		// actually executes the queries (i.e. the INSERT query)
		
		
		$this->_em->flush();
	}

}
